"""empty message

Revision ID: 1a51b763d804
Revises: 
Create Date: 2025-04-01 22:14:07.026459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a51b763d804'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_description'), 'genres', ['description'], unique=False)
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=False)
    op.create_table('film_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_genres_film_id'), 'film_genres', ['film_id'], unique=False)
    op.create_index(op.f('ix_film_genres_genre_id'), 'film_genres', ['genre_id'], unique=False)
    op.create_index(op.f('ix_film_genres_id'), 'film_genres', ['id'], unique=False)
    op.add_column('films', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('films', 'is_active')
    op.drop_column('films', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('films', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('films', 'status')
    op.drop_index(op.f('ix_film_genres_id'), table_name='film_genres')
    op.drop_index(op.f('ix_film_genres_genre_id'), table_name='film_genres')
    op.drop_index(op.f('ix_film_genres_film_id'), table_name='film_genres')
    op.drop_table('film_genres')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_index(op.f('ix_genres_description'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
