"""empty message

Revision ID: 1e059ba461de
Revises: bbdf6afc67e7
Create Date: 2025-03-16 10:23:56.402437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e059ba461de'
down_revision: Union[str, None] = 'bbdf6afc67e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('films', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('films', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('films', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('films', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
