"""empty message

Revision ID: 2780d7d5e1bc
Revises: cb06a58bddec
Create Date: 2025-04-05 01:59:30.591495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2780d7d5e1bc'
down_revision: Union[str, None] = 'cb06a58bddec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('showtime_seat_id', sa.Integer(), nullable=False))
    op.drop_constraint('tickets_showtime_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_seat_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'showtime_seats', ['showtime_seat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tickets', 'seat_status')
    op.drop_column('tickets', 'showtime_id')
    op.drop_column('tickets', 'seat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('seat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('showtime_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('seat_status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_seat_id_fkey', 'tickets', 'seats', ['seat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tickets_showtime_id_fkey', 'tickets', 'showtimes', ['showtime_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tickets', 'showtime_seat_id')
    # ### end Alembic commands ###
