"""xoa id_ticket trong bill va them id__bill trong ticket

Revision ID: 3ad6e5a9e1c6
Revises: 75f839e4e836
Create Date: 2025-04-11 18:03:19.283507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad6e5a9e1c6'
down_revision: Union[str, None] = '75f839e4e836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'staff_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('bills_ticket_id_fkey', 'bills', type_='foreignkey')
    op.drop_column('bills', 'ticket_id')
    op.add_column('tickets', sa.Column('bill_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'bills', ['bill_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'bill_id')
    op.add_column('bills', sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('bills_ticket_id_fkey', 'bills', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bills', 'staff_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
