"""empty message

Revision ID: 86e95e3cea54
Revises: 1a51b763d804
Create Date: 2025-04-02 15:07:24.231378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e95e3cea54'
down_revision: Union[str, None] = '1a51b763d804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('actors', sa.String(), nullable=True))
    op.add_column('films', sa.Column('director', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'director')
    op.drop_column('films', 'actors')
    # ### end Alembic commands ###
