"""empty message

Revision ID: bbdf6afc67e7
Revises: 
Create Date: 2025-03-16 10:15:41.285541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbdf6afc67e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cinema_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'cinemas', ['cinema_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'cinema_id')
    # ### end Alembic commands ###
