"""empty message

Revision ID: c39a92fb5820
Revises: 551d6ec985f7
Create Date: 2025-03-31 16:02:33.534597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39a92fb5820'
down_revision: Union[str, None] = '551d6ec985f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
