"""empty message

Revision ID: cb06a58bddec
Revises: 
Create Date: 2025-04-05 01:18:23.222912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb06a58bddec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtimes', sa.Column('film_id', sa.Integer(), nullable=False))
    op.add_column('showtimes', sa.Column('room_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'showtimes', 'films', ['film_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'showtimes', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.add_column('tickets', sa.Column('seat_status', sa.Boolean(), nullable=False))
    op.drop_constraint('tickets_room_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_film_id_fkey', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'film_id')
    op.drop_column('tickets', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tickets_film_id_fkey', 'tickets', 'films', ['film_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tickets_room_id_fkey', 'tickets', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tickets', 'seat_status')
    op.drop_constraint(None, 'showtimes', type_='foreignkey')
    op.drop_constraint(None, 'showtimes', type_='foreignkey')
    op.drop_column('showtimes', 'room_id')
    op.drop_column('showtimes', 'film_id')
    # ### end Alembic commands ###
