"""comit nhieu qua k nho noi

Revision ID: ccf1961edd45
Revises: 3ad6e5a9e1c6
Create Date: 2025-04-11 18:16:32.115075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf1961edd45'
down_revision: Union[str, None] = '3ad6e5a9e1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'value',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'value',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
