"""empty message

Revision ID: df33b6f58c40
Revises: c39a92fb5820
Create Date: 2025-03-31 17:24:42.410733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df33b6f58c40'
down_revision: Union[str, None] = 'c39a92fb5820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('films', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('films', 'status')
    # ### end Alembic commands ###
